# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duragraph < Formula
  desc "Temporal for AI agents — durable, replayable agent workflows on your infra. Self-hosted, event-sourced, single binary."
  homepage "https://github.com/Duragraph/duragraph"
  version "0.7.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.6/duragraph_0.7.6_darwin_x86_64.tar.gz"
      sha256 "8dfdfe89383fb24f871686d26c700f0efc6a55734b0a0faece64836af42184f2"

      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.6/duragraph_0.7.6_darwin_arm64.tar.gz"
      sha256 "afe6309dcc68a2c66dca2a4f024149b30194c3c81126dbbe1d7de369ea0951b4"

      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.6/duragraph_0.7.6_linux_x86_64.tar.gz"
      sha256 "e70f275c0173e984929391271ca8099bc719f7466518b75daa90595138c0147b"
      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.6/duragraph_0.7.6_linux_arm64.tar.gz"
      sha256 "4603d172f40746a6f1a23bba61b638e6470b1221d6c95883aa8d160e8400459e"
      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Quick start (zero config — embedded Postgres + NATS):
        duragraph dev

      Self-hosted serve mode (uses the config in
      ~/.config/duragraph/config.toml or env vars):
        duragraph serve

      Run as a background service:
        brew services start duragraph

      Documentation: https://github.com/Duragraph/duragraph
    EOS
  end

  service do
    run [opt_bin/"duragraph", "serve"]
    keep_alive true
    working_dir var
    log_path var/"log/duragraph.log"
    error_log_path var/"log/duragraph.error.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/duragraph version")
  end
end
