# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duragraph < Formula
  desc "LangGraph-compatible AI workflow orchestration platform — durable, self-hostable, single binary."
  homepage "https://github.com/Duragraph/duragraph"
  version "0.7.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.2/duragraph_0.7.2_darwin_x86_64.tar.gz"
      sha256 "92bf75a7ae9e9770eac6ebbc8f84ffea588996406095197894d28b95a5f8e1ea"

      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.2/duragraph_0.7.2_darwin_arm64.tar.gz"
      sha256 "124de46e813b579d9f72d7257040a06df85909a11a6040d4f09700a0e6d843b0"

      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.2/duragraph_0.7.2_linux_x86_64.tar.gz"
      sha256 "b881232e750c05d53a4988db080a9ebe869710b8a71f405738f8b8e65d7d92c7"
      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.2/duragraph_0.7.2_linux_arm64.tar.gz"
      sha256 "9c6704fc9995afcb64fbc5a5db3dbc35ed77ea3a3985d2af5af43442a7679450"
      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Quick start (zero config — embedded Postgres + NATS):
        duragraph dev

      Self-hosted serve mode (uses the config in
      ~/.config/duragraph/config.toml or env vars):
        duragraph serve

      Run as a background service:
        brew services start duragraph

      Documentation: https://github.com/Duragraph/duragraph
    EOS
  end

  service do
    run [opt_bin/"duragraph", "serve"]
    keep_alive true
    working_dir var
    log_path var/"log/duragraph.log"
    error_log_path var/"log/duragraph.error.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/duragraph version")
  end
end
