# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duragraph < Formula
  desc "Temporal for AI agents — durable, replayable agent workflows on your infra. Self-hosted, event-sourced, single binary."
  homepage "https://github.com/Duragraph/duragraph"
  version "0.7.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.5/duragraph_0.7.5_darwin_x86_64.tar.gz"
      sha256 "4580888f799f48d8a17dd8d99d3d7305dedc647b7a60de8dc70e698cb67ef061"

      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.5/duragraph_0.7.5_darwin_arm64.tar.gz"
      sha256 "533d1677d0d13f38e68bdc36bbf00e558c7a8c9cff775429e8701e3848d2b439"

      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.5/duragraph_0.7.5_linux_x86_64.tar.gz"
      sha256 "0c64038a5fc51b76b455ee2b96e9b72fc202002e242319b32474883ce464cb73"
      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Duragraph/duragraph/releases/download/v0.7.5/duragraph_0.7.5_linux_arm64.tar.gz"
      sha256 "3dc731b46f662aa46a797982eefe8b85c9542056464f939ec791f1063e66f23a"
      define_method(:install) do
        bin.install "duragraph"
        generate_completions_from_executable(bin/"duragraph", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      Quick start (zero config — embedded Postgres + NATS):
        duragraph dev

      Self-hosted serve mode (uses the config in
      ~/.config/duragraph/config.toml or env vars):
        duragraph serve

      Run as a background service:
        brew services start duragraph

      Documentation: https://github.com/Duragraph/duragraph
    EOS
  end

  service do
    run [opt_bin/"duragraph", "serve"]
    keep_alive true
    working_dir var
    log_path var/"log/duragraph.log"
    error_log_path var/"log/duragraph.error.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/duragraph version")
  end
end
